### ISSUE TITLE
Allow other buffer types to be passed to populateMatrix

### ISSUE THREAD

**Issue by alexshalamov** [w3c/orientation-sensor#20]
The API should not restrict passed data type accepted by populateMatrix to Float32Array.

Proposed idl changes.

```
interface OrientationSensor : Sensor {
  ...
  void populateMatrix(Float32Array or Float64Array or DOMMatrix targetMatrix);
};
```

**Comment by pozdnyakov** [comment]
Can we find a more elegant way, maybe declare `RotationMatrix` as union type covering all types you propose? @kenchris

**Comment by kenchris** [comment]
Yes, we can do that, and that is a common spec way to do that

**Comment by alexshalamov** [comment]
```
typedef (Float32Array or Float64Array or DOMMatrix) RotationMatrix;

interface OrientationSensor : Sensor {
  void populateMatrix(RotationMatrix targetMatrix);
};
```

**Comment by kenchris** [comment]
My only fear is that the platform at somepoint will have a RotationMatrix :-) so maybe we should call it RotationMatrixType or similar. What do other specs do?

**Comment by alexshalamov** [comment]
@kenchris I found only 1 case where typedef is UnionName[Type]. https://www.w3.org/TR/credential-management/#typedefdef-credentialbodytype. We can add postfix, it is only a typedef.

**Comment by kenchris** [comment]
Yes let's do that
