### ISSUE TITLE
Expose quaternion as an attribute

### ISSUE THREAD

**Issue by pozdnyakov** [w3c/orientation-sensor#21]
The BYOB for quaternion does not look quite convenient from the user perspective.
The main reason for the previous using of BYOB was the potential GC issues, now BYOB here seems to be unnecessary: w3c/sensors#153 (comment) so we can consider converting it to an attribute.

Proposal:
`FrozenArray<double>? quaternion;`

client code before:
```

let quat = new Float32Array(4);
sensor.populateQuaternion(quat);
let w = quat[0];

```

after:

`let w = sensor.quaternion[0];`

and for copying:

`let quat = new Float32Array(sensor.quaternion);`

Why `FrozenArray<double>` ?

1. exposes data in immutable way
2. consistent with low-level sensors exposing reading fields as double
3. allows more accurate data

**Comment by pozdnyakov** [comment]
@alexshalamov @kenchris @anssiko wdyt?

**Comment by alexshalamov** [comment]
Looks like an improvement, it is also possible to avoid precision loss:
`let quat = new Float64Array(sensor.quaternion);`
