### ISSUE TITLE
Define populateMatrix algorithm taking into account projection / translation values

### ISSUE THREAD

**Issue by alexshalamov** [w3c/orientation-sensor#24]
If the matrix provided to populateMatrix already contains translation / scale / projection data, specification should define algorithm that will cover such cases, e.g. 

- overwrite everything
- check if is projection => overwrite
- check if translation => keep translation, add rotation

**Comment by pozdnyakov** [comment]
let's keep it simple, either

- overwrite everything

or 

- keep it as it is

**Comment by alexshalamov** [comment]
+1 for overwrite everything. Would be more predictable for web developers than implementing data mining heuristics. Also, some might want to apply translate / scale / rotate in different order, thus, would be better to provide only rotation matrix.

**Comment by pozdnyakov** [comment]
agreed for rewriting everything
