### ISSUE TITLE
Return quaternion as [x,y,z,w]

### ISSUE THREAD

**Issue by pozdnyakov** [w3c/orientation-sensor#29]
Even though a standard form of quaternion representation in math is starting from the real part (i.e. [w,x,y,z]) many of popular WebGL frameworks [1][2][3][4] use a different order of [x,y,z,w]. We probably should be compatible and should update the spec accordingly.

[1] https://doc.babylonjs.com/classes/2.4/quaternion
[2] https://threejs.org/docs/api/math/Quaternion.html
[3] https://www.blend4web.com/api_doc/module-quat.html#.fromValues
[4] http://developer.playcanvas.com/en/api/pc.Quat.html

**Comment by pozdnyakov** [comment]
@alexshalamov @anssiko @kenchris thoughts?

**Comment by alexshalamov** [comment]
sounds like a good idea.

**Comment by kenchris** [comment]
I think it makes a lot of sense. Also in math quaternions are normally represented using i, j and k components, so order doesn't matter, in mathematical sense. If we define just the values (ie no i, j and k), ie. x + yi +zj + wk, the order [x, y, z, w] makes a lot of sense.

The following are valid quaternions:

1
14
312 + 7i (a quaternion and a complex number!)
-1 + 4i - 8j + 8k

Like complex numbers they i**2 == -1 :-) and so it j**2 == -1 and k**== -1 and ijk == -1

**Comment by pozdnyakov** [comment]
in each of your examples the real component stays first and that's the standard representation :)

**Comment by kenchris** [comment]
Yes, I assume that x is used for representing the real component, right?

**Comment by pozdnyakov** [comment]
no, `w` is real, it's equal to `cos(theta)`

**Comment by kenchris** [comment]
Oh, not obvious :-) so is that also the case for the other implementations?

Maybe we should add a note explaining this

**Comment by kenchris** [comment]
https://github.com/mrdoob/three.js/issues/2250

**Comment by pozdnyakov** [comment]
For both math and alphabetical reasons the current order [w,x,y,z]  is correct, however for some reason JS frameworks prefer [x,y,z,w] , so this issue is more about API convenience..

**Comment by pozdnyakov** [comment]
> Maybe we should add a note explaining this

Could you give more details, what such note should contain?

**Comment by kenchris** [comment]
Sure, say how quaternions are represented, ie w + xi + yj + zk, with a scalar w and a vector x, y, z. And then mention that we expose these as vector + scalar, [x, y, z, w] as that is the most prevalent way of doing that when exposed as an array, but that other libraries etc could impose a different order like [w, x, y, z]

**Comment by pozdnyakov** [comment]
Reopen to add an explaining note
