### ISSUE TITLE
Image has weird perspective

### ISSUE THREAD

**Issue by kenchris** [w3c/orientation-sensor#3]
the perspective of the phone sides on that picture in comparison with the earth, looks all wrong. The phone looks like it lays flat on the surface, but the sides tell another story... the sides should be parallel with the z axis

**Comment by alexshalamov** [comment]
Do you want phone to be real size comparing to the Earth size? Or I should make phone curved? The x and y vectors are aligned with the device sides and z points straight from the device. Also coordinate system is aligned with the Earth drawing, you can test it yourself by moving axes to the center of the Earth wireframe.

**Comment by kenchris** [comment]
no, I want the lines of the phone sides (from front to back) to be parallel with the z-axis

**Comment by alexshalamov** [comment]
Could you check PR and tell if it fixes the issue. Thanks.
