### ISSUE TITLE
Use low-level permission tokens for orientation sensors

### ISSUE THREAD

**Issue by alexshalamov** [w3c/orientation-sensor#33]
Based on security research papers, e.g.,[ "TapLogger: Inferring User Inputs On Smartphone Touchscreens Using On-board Motion Sensors"](https://pdfs.semanticscholar.org/c860/4311321f1b8f8fdc8acff8871a5bad2ad4ac.pdf), orientation sensors expose same security risks as the low-level sensors that used for fusion. As there is no grouping provided by the Permission API, each orientation sensor needs set of permissions associated with low-level sensors.

- AbsoluteOrientationSensor - [“accelerometer”, “gyroscope”, “magnetometer”]
- RelativeOrientationSensor - [“accelerometer”, “gyroscope”]
- GeomagneticOrientationSensor - [“accelerometer”, “magnetometer”]

**Comment by alexshalamov** [comment]
@riju @tobie @pozdnyakov @kenchris @anssiko , please take a look.

If Permission API would have grouping in the future, we can name those sets to improve usability (request with 1 token), thus, I think this change is forward / backward compatible.

**Comment by pozdnyakov** [comment]
lgtm
