### ISSUE TITLE
Maybe too restrictive: with a size other than four

### ISSUE THREAD

**Issue by kenchris** [w3c/orientation-sensor#7]
It should be at least size of 4, but I think that people might sometimes reuse structures, like glMatrix has no size checks like this and could happily use a Float32Array of size 10 as a vec3.

**Comment by kenchris** [comment]
This also means that we might want to add an offset to the populate methods.

pupulateQuaternion(targetBuffer, offset)

which will default to 0

**Comment by alexshalamov** [comment]
If I remember correctly WebGL does not use quaternions directly, and vec3 is used for 2d transformations. Do you have other use-cases in mind?

**Comment by kenchris** [comment]
I can have a buffer, which is what webgl usually uses :-) so it can be nice to be able to write directly to this buffer with an offset instead

I can get a vec3 or vec4 directly from a buffer in my shader using gl.getAttribLocation(...), that is quite common actually.

**Comment by alexshalamov** [comment]
Did you mean mat4? vec4 is used to represent vertices or color / position. mat3 can be used for 2d transforms. Btw, getAttribLocation returns id, not a vec4.

If you want to compute something in fragment shader and pass vec4 quat, why not to use populateQuaternion.

If you meant mat3 (2d transform), how would you populate it by the sensor? Would you expect that xy would be used to calculate rotation, why not yz...?

Sensor model operates in 3d space, thus, you need mat4 Float32Array, you can pass it directly to the API, populateMatrix will fill rotation data keeping other transformations intact.

Maybe you have a valid point, but I don't see what concrete use-case it is trying to solve. Maybe we keep issue open for further research. What do you think?

**Comment by kenchris** [comment]
getAttribLocation allows me to tell what is being exposed in the shader. What it returns in JS is of less concern.

vec4 can represent many things, like a color, like a vector, like a quaternion, like a texture... it is just 4 values in the shader, meaning that vec4.a == vec4.x, etc. People do all kinds of weird things in shaders :-)

You upload a buffer in JS and tell how that is exposed in the shader, and the size of each value. So I can say that each 3 values represent a vec3 which it should expose in my shader. That is for instance how I would normally expose a buffer of vertex normals so that I can calculate color which I will interpolate in the fragment shader using a 'varying'.

Anyway, things change and who knows that WebGPU can do, but I think that this limitation is unneeded and I don't see any downside with lifting it

**Comment by pozdnyakov** [comment]
Given the above, think at the moment we could change the size check from `size==4` to `size>=4` and leave adding `offset` for further research. @kenchris @alexshalamov wdyt?

**Comment by kenchris** [comment]
Check my latest update to the comment above. I added a bit more context.

@pozdnyakov I am fine with that, but I think we should consider offset as well, so leave it open

**Comment by anssiko** [comment]
Definitely needs further research.

**Comment by anssiko** [comment]
`pupulateQuaternion()` was since replaced by a [`quaternion`] property, so this issue no longer exists. If you want to use your own buffer of a bigger size, you can.

Closing this issue, @kenchris please feel free to chime in if you have further feedback.

[`quaternion`]: https://w3c.github.io/orientation-sensor/#orientationsensor-quaternion
