### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xfq** [w3c/orientation-sensor#71]
`[QUATERNIONS]` in [Informative References](https://www.w3.org/TR/2021/WD-orientation-sensor-20210603/#informative) returns 500 for me.

/cc @anssiko @kenchris

**Comment by anssiko** [comment]
Given this math concept is informative, proposing to replace this with https://en.m.wikipedia.org/wiki/Quaternion

@xfq appreciate your PR to fix.
