### ISSUE TITLE
Clicking on Alex goes to https://intel.com, click on others goes to intel.com without https://

### ISSUE THREAD

**Issue by kenchris** [w3c/orientation-sensor#9]
SSIA

**Comment by alexshalamov** [comment]
:D stop clicking on me. What should be the correct url? @anssiko ?

**Comment by kenchris** [comment]
I actually saw it when hovering :-) - I would say always use https://

**Comment by anssiko** [comment]
You can use https://validator.w3.org/checklink to check the links are valid. No https sadly for intel.com yet.
